# Site settings
title: Ethan's Profile
email: cpompey1998@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Local. Social. Mobile!
baseurl: "/patchwork-gh-pages-24"
url: "http://mmontoya1996.github.io"
twitter_username: @cpompey115
Instagrma_username:  @cpompey115
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
